Setup of Antora as a documentation site
keycloak/keycloak-benchmark pull request #127
Opened 2022-07-06 09:45 UTC by ahus1

This add a minimal setup for [Antora](https://antora.org/). Please see it as a PoC how this tool can help this project. Once this PoC is accepted, the documentation content of the project will be moved into the new structure.

All documentation content for the site is in the folder `/doc`. 

The scripts and templates to create a documentation site are in `/antora`, including a minimal description how to create a local preview. 

While this PR is in the draft mode, the site is published here: https://ahus1.github.io/keycloak-benchmark/

To have some demoable content, the big `README.adoc` about the minikube setup is broken down to separate pages in the `kubernetes` module. That content is available here: https://ahus1.github.io/keycloak-benchmark/kubernetes-guide/latest/index.html; use the navigation on the left to browse through the different pages.

Closes #125

To leave the draft state, the following needs to be completed: 

* [ ] approval from maintainers to use Antora as a tool within Keycloak Benchmark
* [ ] enabling GitHub pages for the keycloak-benchmark GitHub project (can only be done by an admin)
* [ ] remove demo content and replace with the real content 
* [ ] update the `antora-playbook.yaml` with repository and branch information of the Keycloak organisation

2022-07-06 09:50 UTC, ahus1 commented
@kami619 - I'd like you to take a view at this approach before I involve other maintainers. Thanks!

2022-07-07 13:47 UTC, ahus1 commented
Unfortunately Antora doesn't come with a dark mode by default, still I can brush up my CSS skills create a minimal dark mode. Should it auto-detect the dark mode of the browser (simpler) or would we need to have a UI switch for that (more complicated, would probably need JavaScript and a cookie, and might flicker)?

2022-07-07 14:14 UTC, ahus1 commented
Hi @pedroigor / @mposolda / @tkyjovsk / @hmlnarik / @stianst - this issue suggests to use Antora to create a static site to present the information about how to run performance tests and setup environments. Please comment hear with your thoughts.

The elevator pitch:

> The documentation is currently scattered in multiple places, and the README for minikube is getting quite big and should be splitted.
Antora will prepare a static site that sources AsciiDoc content from the repository, and present this is a clean, topic-based and structured way. Each component in Antora is versioned, so we can have a set of documentation for each release of the project.

2022-07-07 14:46 UTC, kami619 commented
> Unfortunately Antora doesn't come with a dark mode by default, still I can brush up my CSS skills create a minimal dark mode. Should it auto-detect the dark mode of the browser (simpler) or would we need to have a UI switch for that (more complicated, would probably need JavaScript and a cookie, and might flicker)?

I wouldn't say this needs to be a necessity for us to begin with, if Antora doesn't do it provide this out-of-box, also, there are tons of browser plug-ins which auto-convert the pages to be in dark mode. This change looks fine to me to pursue, if rest of the Maintainers are ok with it as well.

2022-07-28 11:00 UTC, stianst commented
Sorry about the super late reply to this one.

My personal take on this is that it seems a bit overkill at least at the moment, and I'm not super exited about using yet another tool-chain to build docs. A long time ago I looked at Antora, but found that it didn't serve our needs for the main docs at the time. One main thing was that I didn't really want to bring in Node as a requirement to build the docs, and wanted something that can be bundled within Maven.

Did you consider just using AsciiDoc with the Maven plugin like we do for the other docs?

What would be the benefits (not general Anotora selling points, but to us in general) to using Antora for these docs? If there's bunch of nice things it brings, then we could perhaps also consider using it for the main docs?

2022-08-18 09:28 UTC, stianst approved these changes

2022-08-18 10:52 UTC, ahus1 commented
As discussed today, Antora could bring in a good way to publish versioned guides, and eventually also other documentation in a searchable way (both on site and via Google). Antora works best (and fast) when all AsciiDoc content is stored in a Git repository, so all Freemarker templating should have been done already. 

Let's use this as a seed what can be done, and then see how it can be combined with other parts like the guides. 

Once I've brushed up this PR I'll ping you to configure GitHub pages for this repo.

2022-08-19 12:17 UTC, ahus1 commented
@stianst - thanks for approving the use of Antora. 

To allow this repository to publish its contents, please enable GitHub pages in the new (beta) "GitHub Actions" mode - this one doesn't require a `gh-pages` branch any more, and is already enabled in the builds added by this PR: 

![image](https://user-images.githubusercontent.com/3957921/185616554-94e3dea4-9485-4e60-9907-b7dfda76434a.png)

Thanks!

2022-08-19 12:19 UTC, ahus1 commented
@kami619 - I copied over the latest docs from the different areas to this PR, squashed it, and it now should be ready to be merged. 

I published a preview here: https://ahus1.github.io/keycloak-benchmark/

Please give it one final approval. Once the changes to GitHub pages have been done, this can then be merged. 

Thanks!

2022-08-19 14:32 UTC, ahus1 commented
Stian just updated the repo settings, so this PR should be ready to merge once @kami619 had a final look at the content.

2022-08-22 15:37 UTC, kami619 commented
Right now, we could probably default to the `About` page under the `Kubernetes Guide` section, instead of the welcome page.

Welcome Page:
![image](https://user-images.githubusercontent.com/3415105/185961194-493e29d0-ca68-4c48-b170-f44dbf241ede.png)

About Page:
![image](https://user-images.githubusercontent.com/3415105/185961294-84ebff84-db2c-47ec-a136-39577b31cc1c.png)

2022-08-22 15:39 UTC, kami619 commented
This doesn't need to be in this PR, but seems like so much vital info is buried under the `Other information` section of the `Kubernetes Guide`, it would be worth while to create separate sections of their own to be coming up on the left pane window

![image](https://user-images.githubusercontent.com/3415105/185961683-440c38ec-37f1-4f8b-ae1a-233ce8f24e81.png)

2022-08-22 15:44 UTC, kami619 commented
If I click on http://localhost:5000/keycloak-benchmark/benchmark-guide/latest/#report the `getnerate-custom-report.sh` link, it seems to be downloading the script, instead of routing me to the path of the script. Is that an expected behavior ? It seems to be different to the behavior when the href's are associated with a `.java` classes

2022-08-22 15:46 UTC, kami619 commented
thats the end of my review.

2022-08-22 15:47 UTC, kami619 requested changes
some minimal changes needed based on the previous comments

2022-08-22 19:26 UTC, kami619 approved these changes
lgtm

2022-08-22 19:26 UTC, merged

2022-08-23 08:41 UTC, ahus1 commented
It's alive! :tada: 

https://www.keycloak.org/keycloak-benchmark/