CIAM-3813 Scripts for measuring Keycloak startup time and memory footprint on Minikube
keycloak/keycloak-benchmark pull request #295
Opened 2023-02-16 19:07 UTC by tkyjovsk

2023-02-17 09:20 UTC, kami619 requested changes
thank you sending this PR, it improves the way we can measure start time and memory footprint of the keycloak application confidently. Please add some docs and we can take another stab at it.

2023-02-28 09:00 UTC, kami619 commented on provision/minikube/Taskfile.yaml
> +  KC_SCALE: '{{default "1" .KB_SCALE}}'
looks like this should be `KC_SCALE: '{{default "1" .KC_SCALE}}'` seems like a typo for KB_SCALE

2023-02-28 09:14 UTC, kami619 commented on provision/minikube/measure/collect-sut-info.sh
> +echo "- pods/keycloak-0"
could this be configurable to be fetching the information about other keycloak pods when the KC_SCALE value is greater than 1 ?

2023-02-28 09:22 UTC, kami619 commented on provision/minikube/measure/measure-memory-usage.sh
> +      echo "Pod '${pod}' already exceeded measurement time of ${measurementTime} seconds after start. Skipping."
looks like when I run it, it spits out the `Pod already exceeded measurement time` message by default

```
]$ ./measure-memory-usage.sh
Opening pod detection window for 60 seconds.
Detected new pod 'keycloak-0'.
Detected new pod 'keycloak-1'.
Measuring memory usage for pod 'keycloak-0', UID: 50715a08-3f34-4ac5-8c1c-0224fa1ca1fe.
Measuring memory usage for pod 'keycloak-1', UID: 812e372d-ab34-4fda-9091-09a9c74b02a0.
Pod 'keycloak-1' already exceeded measurement time of 30 seconds after start. Skipping.
Pod 'keycloak-0' already exceeded measurement time of 30 seconds after start. Skipping.
Pod 'keycloak-1' already exceeded measurement time of 60 seconds after start. Skipping.
Pod 'keycloak-0' already exceeded measurement time of 60 seconds after start. Skipping.
Pod 'keycloak-1' already exceeded measurement time of 90 seconds after start. Skipping.
Pod 'keycloak-0' already exceeded measurement time of 90 seconds after start. Skipping.
Pod 'keycloak-1' already exceeded measurement time of 120 seconds after start. Skipping.
Pod 'keycloak-0' already exceeded measurement time of 120 seconds after start. Skipping.
Measuring memory usage for pod 'keycloak-1' finished.
Measuring memory usage for pod 'keycloak-0' finished.


```

2023-02-28 09:49 UTC, kami619 commented on provision/minikube/measure/scale-and-measure-loop.sh
> +scale=${1:-1}
this script could add a section for help to understand the params better, it would skip memory management if its run without any args

2023-02-28 09:51 UTC, kami619 commented on provision/minikube/measure/compute-stats.sh
> +for csvFile in $(find "${dataDir}" -path "**/keycloak-*/**" -name memory-usage-cgroups.csv -o -name memory-usage-rss.csv -o -name startup-times.csv ); do
is there any dependency on other script to be run first for this to be useful ? I am not entirely clear of the sequence of scripts to be consumed in a right order

2023-09-07 17:08 UTC, ahus1 commented
Closing as probably out of date and with conflicts. Please re-open if work continues with this PR.

2023-09-07 17:08 UTC, closed without merging